language: node_js

sudo: false

node_js:
    - "6"
    - "8"

script: "npm run travis"

after_success:
    - npm run coverage

matrix:
    fast_finish: true

cache:
    directories:
        - node_modules
